### PR TITLE
ONL Support for Interface Masters Niagara 2972 Family devices.

### PR DESCRIPTION
**Pull request by vitalivanov**
This is first attempt to port ONL to x86_64 Niagara 2972 family devices:
http://www.interfacemasters.com/products/switches/niagara-2948-12xlm-ocp-product-family.html

For now it's part 1 - only ONL/ONIE installer changes.
No platform, this is WIP.

The installer.sh is modified to support grub. Changes are separated from powerpc not to affect existing platforms.

Open for comments to make sure that I'm moving in correct direction. Small things will be corrected on the way.

### CODE REVIEW

**Comment by nshopik** [comment]
@vitalivanov there is plans to move to LTS kernel (3.14) at some point, see issue #55

**Comment by vitalivanov** [comment]
@nshopik it should be fine to move to any other LTS once we have driver support for IMT platforms.
Once ONL guys switch to another kernel I can make sure kernel is functioning correctly with full driver set support.

**Comment by vitalivanov** [comment]
Any news on this?

**Comment by nshopik** [comment]
@vitalivanov this no longer applies, you need re-base.
@capveg ping

**Comment by jnealtowns** [comment]
Vitaliy,

I am currently in the process of integrating the x86_64 infrastructure into
ONL. As such there may be some conflicts with the architecture-specific
code you've already created in your pull request.

I will let you know as soon as we can accept or provide a rebase from which
you can resubmit your pull request. We appreciate your contribution and
will try to get your work integrated as soon as possible.

Thanks,
Jeff

**Comment by vitalivanov** [comment]
This is merged as:
https://github.com/opennetworklinux/ONL/pull/174

Closing.

**Pull request closed without merging**
