### PR TITLE
Add AS7512-32x-1-r0

### PR DESCRIPTION
**Pull request by jeankuo**

### CODE REVIEW

**Comment by jnealtowns** [comment]
@jeankuo Can you describe which box/chipset the AS7512-32X is? And it seems strange that the identifier would be 32x-1-r0. What is the significance of the -1- between the 32x and r0? This naming convention is different from all existing Accton systems. 

Assuming that the identifier is correct, this pull request looks like a copy and paste from the 6712-32x-r0. In general that is fine, but there are still several identifiers and strings in the pull request which say "6712" instead of "7512".

**Comment by jeankuo** [comment]
@jnealtowns Yes, It is almost copy from AS6712-32X.
AS7512-32X is a new machine and the CPU is the same with AS6712-32X, but MAC is different.
My first target is to setup an environment to let the new machine can load ONL by ONIE.

Naming : AS7512-32X-1-r0, here “-1” is that if the hardware change to cause the software design change, the number ”-1” will push to next number ”-2”. This naming rule is decided from our marketing, and our ONIE development also follows the decision now.
  
About : but there are still several identifiers and strings in the pull request which say "6712" instead of "7512". 
You means that this pull request’s files includes 6712 string ?  I find them, I will change them and send new pull request again. I will close current pull request, and is it ok ?

**Comment by jnealtowns** [comment]
@jeankuo Thank you for the comments. The "-1" strategy seems strange to me. The board revision identifier (r0) already encodes this properly. 

The first version hardware version should be as7512-32x-r0. If there is a hardware change that causes a software change, then the next version should be as7512-32x-r1. This is why the revision number (rX) is part of the identifier. 

Why ignore the current revision system (-r0, -r1, -r2) and invent a new one (-1-r0, -2-r0)?

**Comment by jeankuo** [comment]
@jnealtowns  Yes, you are right. I am mixed up. After check with PLs, this "as7512-32x-1" is only the machine name, but the "-1" is not good design, so we will change the naming. It is still under discussion. So, I will close the pull request. After the discussion, I will raise new pull request. Thanks.

**Comment by jnealtowns** [comment]
@jeankuo Sounds good. I think it would be great if you kept to the existing system for hardware revisions:
x86_64-accton_as7512_32x-r0
x86_64-accton_as7512_32x-r1
x86_64-accton_as7512_32x-r2

**Pull request closed without merging**
