### PR TITLE
Preliminary OpenFlow Agent and OF-DPA support

### PR DESCRIPTION
**Pull request by capveg**
Reviewer: @jnealtowns @rlane 

OF-DPA Closed source binaries now available from apt.opennetlinux.org
* `sudo apt-get update && sudo apt-get install ofdpa-2.0-closed ofdpa-tools indigo-ofdpa-ofagent`
* /usr/sbin/ofdpa-$PLATFORM is the OF-DPA daemon; currently only "powerpc-quanta-ly2-r0" and "powerpc-accton-as5710-54x-r0" are supported
* /lib/powerpc-linux-gnu/libofdpa_rpc_client.so.1 is the library that OFDPA clients link against
* /usr/include/ofdpa-2.0/ofdpa_{api,datapath}.h are the headers that OFDPA clients link against
* /lib/modules/3.9.6-OpenNetworkLinux-85xx/ofdpa/linux-{kernel,user}-bde.ko are the kernel modules

OF-DPA Tools:
* A list of `client_*` utilities for manually populating and interrogating OF-DPA tables
    * /usr/bin/client_flowtable_dump is particularly useful :-)

Two Open Source OpenFlow Agents:
* /usr/sbin/brcm-indigo-ofdpa-ofagent is the stock OpenFlow agent from the OF-DPA distribution.
   * It uses an old branch of Indigo and Loxi from ~2 years ago
   * Has had more testing than the indigo-ofdpa-ofagent binary
* /usr/sbin/indigo-ofdpa-ofagent is the example OpenFlow agent as an OFDPA client
   * based on updated/current Indigo (http://github.com/floodlight/indigo) code
   * source code for the Indigo<-->OFDPA driver is available from: https://github.com/opennetworklinux/ofdpa-.0/tree/master/modules/indigo_ofdpa_driver/module/src
    * Needs more testing -- next is to write oftests for it

Lots of bugs to fix, but I thought I would get the ball rolling
* Need to start oftest testing
* Need to go back and fixup the ROBS_HACK defines
* Currently no support for 1G or other interesting optics

Extra thanks to everyone at Broadcom, Accton, Saurav, Jeff and Rich who helped make this happen!

### CODE REVIEW

**Comment by samrussell** [comment]
Awesome! Waiting eagerly for the AS5710 version ;)

Fails on AS5710 (most likely because it isn't a Quanta, but worth a try) - if anything, confirms that the package apt-get installs from repo correctly

root@onl-powerpc:~# ofdpa-powerpc-quanta-ly2-r0

version 0.0.0.0 -- Built on Tue May 12 2015 at 05:54:50 UTC

Initializing the system.
Error: could not load module linux-kernel-bde.ko: No such file or directory
Error: could not load module linux-user-bde.ko: No such file or directory
open /dev/linux-user-bde: : No such file or directory
sdkCustomInit: ERROR: PCI SOC device probe failed
systemMappingInit: Error initializing driver, rc = -1.
Initialization failed!  Aborting.

**Comment by Lewis-Kang** [comment]
Hi, as I know, OFDPA for AS5710 has been ready but not published yet

**Comment by HamadiSE** [comment]
Hi,

Thank you for making the of-dpa available.
Is it available for this switch QuantaMesh T3048-LY2 or  QuantaMesh
T3048-LY2R ?

Thank you in advance.

2015-06-07 14:50 GMT-04:00 Rob Sherwood <notifications@github.com>:

> Merged #108 <https://github.com/opennetworklinux/ONL/pull/108>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opennetworklinux/ONL/pull/108#event-324731089>.
>



-- 
Salaheddine

**Comment by capveg** [comment]
This is available and should work out of the box on the QuantaMesh LY2 but
not the LY2R.  Hope that helps,

- Rob
.

**Comment by ahmedcs** [comment]
Hello Rob,

Any plans for supporting 1Gb Accton AS4600-54T platform?!

If not, is there any guidelines how to port the indigo agent to this platform.

Any help will be greatly appreciated.

Thanks and best regards,

**Comment by Lewis-Kang** [comment]
Hi ahmedcs, 
AS4600-54T is 1Gb for ports 1~48 already, isn't it?

**Comment by Lewis-Kang** [comment]
Hi Rob,
We have let AS4600-54T support OFDPA. 
Do we need to give you the binary for you to integrate it to ONL?
Or anything else?

**Comment by capveg** [comment]
Hi Lewis,

Yes, that would be great.  If you would please put the ofdpa binary in the
shared closed repository that we have 'ofdpa-2.0-closed-accton', then I can
include it as part of the ONL distribution by default.  If you have support
for any other platforms, put it in the repository as well and I'll throw
them all together.

Thanks!

- Rob
.

**Comment by Lewis-Kang** [comment]
Hi Rob,
I found the files in repository 'ofdpa-2.0-closed-accton' can not tell the OFDPA released version detailed enough. For example, OFDPA has 2.0-EA1 and 2.0-EA2 releases. Do I use the filenames to indicate it? or I just put the latest (2.0-EA2) there?

**Comment by capveg** [comment]
All you have to do is put the files there (with what ever file name you
want) and I will figure it out :-)

- Rob
.

**Comment by ahmedcs** [comment]
Hello lewis,

Thanks for the prompt reply,

Yes it is 1 Gbps for 48 ports, we got two of them

May i ask, Are you with edge-core(accton) or have similar model operational
under ONL?!

Can you help me with getting hardware forwarding to work under ORC?!

FYI: issues #120 And #126 are related

Thanks

On Tuesday, July 28, 2015, Lewis-Kang <notifications@github.com> wrote:

> Hi ahmedcs,
> AS4600-54T is 1Gb for ports 1~48 already, isn't it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opennetworklinux/ONL/pull/108#issuecomment-125430404>.
>


-- 
------------------------------------------------------------------------------------------------------




*Ahmed Mohamed Abd Elmoniem Sayed Assistant Lecturer, CS Department Faculty
of Computers and Information Assiut University, Egypt*
*Mob. No. : **+201009491135*

*E-mail : ahmedcs@aun.edu.eg <ahmedcs@aun.edu.eg> or ahmedcs@ieee.org
<ahmedcs@ieee.org> or ahmedcs982@hotmail.com <ahmedcs982@hotmail.com> or
ahmedcs982@gmail.com <ahmedcs982@gmail.com> University Webpage :
http://www.aun.edu.eg/membercv.php?M_ID=4261
<http://www.aun.edu.eg/membercv.php?M_ID=4261>*

**Comment by Lewis-Kang** [comment]
Hi ahmedcs,
I have no experience on ORC yet. I'd like to check what's going on when I have time too

**Comment by Lewis-Kang** [comment]
Hi Rob,
I have put ofdpa binaries for as4600, as5710, as5712 devices to repository 'ofdpa-2.0-closed-accton'.

**Comment by ahmedcs** [comment]
Great news, looking forward to use it soon.

Hope rob can update the master repo and makefiles so we can build it soon,
sorry to ask but any idea when would be avaliable, Rob?!

Thanks to both of you guys

On Tuesday, July 28, 2015, Lewis-Kang <notifications@github.com> wrote:

> Hi Rob,
> I have put ofdpa binaries for as4600, as5710, as5712 devices to repository
> 'ofdpa-2.0-closed-accton'.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opennetworklinux/ONL/pull/108#issuecomment-125485172>.
>


-- 
------------------------------------------------------------------------------------------------------




*Ahmed Mohamed Abd Elmoniem Sayed Assistant Lecturer, CS Department Faculty
of Computers and Information Assiut University, Egypt*
*Mob. No. : **+201009491135*

*E-mail : ahmedcs@aun.edu.eg <ahmedcs@aun.edu.eg> or ahmedcs@ieee.org
<ahmedcs@ieee.org> or ahmedcs982@hotmail.com <ahmedcs982@hotmail.com> or
ahmedcs982@gmail.com <ahmedcs982@gmail.com> University Webpage :
http://www.aun.edu.eg/membercv.php?M_ID=4261
<http://www.aun.edu.eg/membercv.php?M_ID=4261>*

**Comment by ahmedcs** [comment]
@capveg  
Hello Rob,

Any updates (or estimated time) about the support for the new binaries in the master repository to build a new ONL OFDPA for these switches.

Thanks and best regards,

**Pull request merged**
