### PR TITLE
Add corenet platform and t2080rdb support

### PR DESCRIPTION
**Pull request by shengzhou**
1. patch 'Add Freescale corenet support' is to add freescale corenet support(e500mc, e5500, e6500 core) ,  so previous 'components/powerpc/linux/kernel-e500mc/' can be removed later.
2. patch 'Add ONL support on Freescale T2080RDB platform' is to enable ONL on T2080RDB to provide a reference for any switch based on T2080 SoC.

### CODE REVIEW

**Comment by capveg** [comment]
Hi and thanks for the port!  We're up against a bunch of deadlines for the OCP workshop on 10/9.  Do you mind if we start looking at this after then?

**Comment by shengzhou** [comment]
Thanks Rob, It's okay.

**Comment by sonoble** [comment]
Hi,

We don't currently support the 4.1.3 kernel, how would you like to proceed?

**Comment by shengzhou** [comment]
This pull request was verified with 4.1.3 kernel on T2080RDB, actually, it's up to which kernel version would be the next ONL release.  this pull request is just for a reference, it's easy to port to other kernel version if needed.

**Comment by jnealtowns** [comment]
This version of ONL is no longer supported. 
Please see https://github.com/opencomputeproject/OpenNetworkLinux.

**Pull request closed without merging**
