### PR TITLE
add onlp to swi for accton as5812-54x/as6812-32x

### PR DESCRIPTION
**Pull request by jeankuo**
before merge, remember to put .deb, otherwise build will fail.

### CODE REVIEW

**Comment by sonoble** [comment]
Hi Jeankuo,

I am unable to compile onlp-x86-64-accton-as6812-32x-r0, as5812-54x compiles fine.  It appears there are some fixes around a compile issue in the 5812 that are not in the 6812.  Can you check this for me?

**Comment by jeankuo** [comment]
Dear Steven,

In local test, the output onlpdump binary are both fine for as6812-32x and as5812-54x.
Could you show the compile issue here ?  It is convenient for us to debug this . Thanks.

By the way, I does not have right to access onlp-accton,. It is not convenient for me to test and debug.
If it is possible to let me join the onlp-accton group to faster the job’s going. Thanks.

**Comment by sonoble** [comment]
Hi, 

I added you to the group. I pulled onl and went into https://github.com/opennetworklinux/ONL/tree/master/components/amd64/onlp/onlp-x86-64-accton-as6812-32x-r0 and ran make. It fails due to a compilation error see line 80 in thermali.c in the private as5812 code. 

#if 0 /* Temprarily comment below function to avoid compiler error

**Comment by brandonchuang** [comment]
Hi Steven,

It looks like we use different ways to compile onlp.
I always run make under ~/ONL/onlp-accton/targets/x86_64_accton_as6812_32x/onlpdump$
I also saw the same error as yours before when I was porting as5812-54x.
But the error disappeared when I was porting as6812-32x several days later, so I thought the problem has been fixed with my compile method.
That’s way I did not comment out onlp_file_read_int_max in thermali.c of as6812-32x.
Jeff and I just discussed this in the attached mail.
Can we check with Jeff about how to fix the problem in both compile methods?

Brandon

**Comment by sonoble** [comment]
Hi Brandon,

We are getting ready to move to a new repo, so a lot of things will change, possibly we should delay putting this in until the new repo is up?  You can see generally what it looks like at https://github.com/sonoble/OpenNetworkLinux .. the accton platforms live in https://github.com/sonoble/OpenNetworkLinux/tree/master/packages/platforms/accton and here is where thermali.c moved to : https://github.com/sonoble/OpenNetworkLinux/blob/master/packages/platforms/accton/x86-64-accton-as5712-54x/onlp/builds/src/module/src/thermali.c

**Comment by jeankuo** [comment]
Dear Steven,

To complete this item, in this stage, we(Brandon and Me) prefer to modify as6812-32x like as5812-54x to fix complier error.
Is it ok for you ? Thanks.

/Jean

**Comment by sonoble** [comment]
I am comfortable with that fix.  We just need to be able to compile the deb to put it on the repo.

**Comment by jeankuo** [comment]
Dear Steven,

OK. We will modify it. By the way, When do you plan to transfer to new platform ?

**Comment by brandonchuang** [comment]
Hi Steven,

I just sent the pull request for as5812-54t and as6812-32x to avoid the compile error.
Please help to merge it.
Thanks.

Brandon

**Comment by sonoble** [comment]
debs have been built and uploaded to repo.

**Pull request merged**
