### PR TITLE
add onlp to swi for accton as5812-54t

### PR DESCRIPTION
**Pull request by jeankuo**
before merge, remember to put .deb, otherwise build will fail.

### CODE REVIEW

**Comment by sonoble** [comment]
btw, I don't have any info on these platforms and they don't appear to be annouced.  I am adding them to the supported docs but without processor/chip info..

<tr> <td> Accton AS5812-54T       <td> 48x10G + 6x40G   <td> UNK <td> UNK      <td> Supported </tr>
<tr> <td> Accton AS5812-54X       <td> 48x10G + 6x40G   <td> UNK <td> UNK      <td> Supported </tr>
<tr> <td> Accton AS6812-32X       <td> 32x40G           <td> UNK <td> UNK      <td> Supported </tr>

**Comment by jeankuo** [comment]
OK. Thanks.

**Comment by sonoble** [comment]
No problem, ping us when you want to update the information.

**Comment by wally-wang-accton** [comment]
Dear Steven,

AS5712-54X -> AS5812-54X
AS5812-54T is same as AS5812-54X, but change 48x10G fiber to 48x10G copper.

AS6712-32X -> AS6812-32X

We only upgrade MAC chip from Trident2 to Trident2+ for these platforms.  Please reference as below:


Accton AS5812-54T

48x10G + 6x40G

Intel Rangely C2538 x86

Broadcom BCM56864 (Trident2+)

Supported

Accton AS5812-54X

48x10G + 6x40G

Intel Rangely C2538 x86

Broadcom BCM56864 (Trident2+)

Supported

Accton AS6812-32X

32x40G

Intel Rangely C2538 x86

Broadcom BCM56860 (Trident2+)

Supported


Best Regards,
Wally

**Pull request merged**
