### PR TITLE
Add support Quanta LY6 x86 and LY8 x86 (rangeley cpu board)

### PR DESCRIPTION
**Pull request by audihsu-qci**

### CODE REVIEW

**Comment by sonoble** [comment]
Hi,

I attempted to build your image and ran into the following issue:

WARNING:onlpkg:no matching packages for onlp-x86-64-quanta-ly6-rangeley-r0 (amd64)
INFO:onlpkg:found at /home/snoble/git.updates/ONL.Quanta/ONL/components/amd64/onlp/onlp-x86-64-quanta-ly6-rangeley-r0/deb/debuild/debian
INFO:onlpkg:can be built locally at /home/snoble/git.updates/ONL.Quanta/ONL/components/amd64/onlp/onlp-x86-64-quanta-ly6-rangeley-r0
make[2]: Entering directory `/home/snoble/git.updates/ONL.Quanta/ONL/components/amd64/onlp/onlp-x86-64-quanta-ly6-rangeley-r0'
/home/snoble/git.updates/ONL.Quanta/ONL/submodules/infra/builder/unix/dependmodules.mk:65: /x86_64_quanta_ly6_rangeley_r0.mk: No such file or directory
make[3]: *** No rule to make target `/x86_64_quanta_ly6_rangeley_r0.mk'.  Stop.

**Comment by audihsu-qci** [comment]
Hi,
    I think the submodule/only-quanta is checked out to previous commit.
    May you try to make submodule/only-quanta dirty and keep module and target, or add a onl commit to check out the latest only-quanta commit

Regards,
    Audi Hsu


sonoble <notifications@github.com<mailto:notifications@github.com>> 於 2015年10月24日 上午7:01 寫道：


Hi,

I attempted to build your image and ran into the following issue:

WARNING:onlpkg:no matching packages for onlp-x86-64-quanta-ly6-rangeley-r0 (amd64)
INFO:onlpkg:found at /home/snoble/git.updates/ONL.Quanta/ONL/components/amd64/onlp/onlp-x86-64-quanta-ly6-rangeley-r0/deb/debuild/debian
INFO:onlpkg:can be built locally at /home/snoble/git.updates/ONL.Quanta/ONL/components/amd64/onlp/onlp-x86-64-quanta-ly6-rangeley-r0
make[2]: Entering directory /home/snoble/git.updates/ONL.Quanta/ONL/components/amd64/onlp/onlp-x86-64-quanta-ly6-rangeley-r0'
/home/snoble/git.updates/ONL.Quanta/ONL/submodules/infra/builder/unix/dependmodules.mk:65: /x86_64_quanta_ly6_rangeley_r0.mk: No such file or directory
make[3]: *** No rule to make target/x86_64_quanta_ly6_rangeley_r0.mk'. Stop.

**Comment by sonoble** [comment]
Hi Audi,

I tried again and the LY2 builds fine but the LY6 does not.

Processing onlp-powerpc-quanta-ly2-r0_0.2.0bsn1~ubuntu1_powerpc.deb...
Signed deb onlp-powerpc-quanta-ly2-r0_0.2.0bsn1~ubuntu1_powerpc.deb
Packages Signed
/home/snoble/git.updates/changes/ONL.Quanta/tools/onlpkg.py --add-pkg *powerpc*.deb
INFO:onlpkg:adding new package onlp-powerpc-quanta-ly2-r0_0.2.0bsn1~ubuntu1_powerpc.deb...
rm *powerpc*.deb
rm -rf debuild/debian/tmp debuild/debian/onlp-powerpc-quanta-ly2-r0/ debuild/debian/onlp-powerpc-quanta-ly2-r0-dbg || echo rm failed
make[2]: Leaving directory `/home/snoble/git.updates/changes/ONL.Quanta/components/powerpc/onlp/onlp-powerpc-quanta-ly2-r0'
INFO:onlpkg:extracting /home/snoble/git.updates/changes/ONL.Quanta/debian/repo/powerpc/onlp-powerpc-quanta-ly2-r0_0.2.0bsn1~ubuntu1_powerpc.deb...
WARNING:onlpkg:no matching packages for onlp-x86-64-quanta-ly6-rangeley-r0 (amd64)
INFO:onlpkg:found at /home/snoble/git.updates/changes/ONL.Quanta/components/amd64/onlp/onlp-x86-64-quanta-ly6-rangeley-r0/deb/debuild/debian
INFO:onlpkg:can be built locally at /home/snoble/git.updates/changes/ONL.Quanta/components/amd64/onlp/onlp-x86-64-quanta-ly6-rangeley-r0
make[2]: Entering directory `/home/snoble/git.updates/changes/ONL.Quanta/components/amd64/onlp/onlp-x86-64-quanta-ly6-rangeley-r0'
/home/snoble/git.updates/changes/ONL.Quanta/submodules/infra/builder/unix/dependmodules.mk:65: /x86_64_quanta_ly6_rangeley_r0.mk: No such file or directory
make[3]: *** No rule to make target `/x86_64_quanta_ly6_rangeley_r0.mk'.  Stop.

**Comment by audihsu-qci** [comment]
Hi sonoble,
    Try to check these paths
submodules/onlp-quanta/modules/x86_64_quanta_ly6_rangeley_r0
submodules/onlp-quanta/modules/x86_64_quanta_ly8_rangeley_r0
submodules/onlp-quanta/targets/x86_64_quanta_ly6_rangeley_r0
submodules/onlp-quanta/targets/x86_64_quanta_ly8_rangeley_r0

As I mentioned, while you are building onlp deb, corresponding onlp-quanta folder will be checked out to specific commit.
Take a look at onlp-quanta pull request https://github.com/opennetworklinux/onlp-quanta/pull/5
This might help.

**Comment by sonoble** [comment]
Hi,

Sorry about that, I missed the patch for onlp-quanta.  I have applied it and am running the build now, seems to be working.  Will update as soon as it is done.

**Comment by sonoble** [comment]
Build was successful, thank you for your contribution.

**Comment by sonoble** [comment]
Hi Audi,

I tried to boot this on an LY8 and it failed:

Setting up base platform configuration for x86-64-quanta-ly8-rangeley-r0...
update-rc.d: using dependency based boot sequencing
update-rc.d: using dependency based boot sequencing
hwclock: select() to /dev/rtc0 to wait for clock tick timed out: Success
BUG: unable to handle kernel NULL pointer dereference at 0000000000000080
IP: [<ffffffff80285c5c>] gpiod_request+0x1ac/0x1f0
PGD 1798e7067 PUD 179968067 PMD 0
Oops: 0000 [#1] SMP
Modules linked in:
CPU 4
Pid: 2810, comm: systemled Not tainted 3.9.6-OpenNetworkLinux #1 Quanta Quanta LY8 (1LY8UZZ000E)
RIP: 0010:[<ffffffff80285c5c>]  [<ffffffff80285c5c>] gpiod_request+0x1ac/0x1f0
RSP: 0018:ffff88016a205e18  EFLAGS: 00010086
RAX: 0000000000000000 RBX: ffffffff80bbe670 RCX: ffffffff807c0796
RDX: ffffffff80bbe670 RSI: ffffffff807c8a08 RDI: ffffffff80a73a40
RBP: ffff88016a205e48 R08: 00000000fffffdfb R09: 0000000000000002
R10: 000000000000000a R11: f000000000000000 R12: 0000000000000000
R13: 00000000fffffdfb R14: 0000000000000282 R15: ffffffff807c0796
FS:  00007f441e3c2700(0000) GS:ffff88017fd00000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
CR2: 0000000000000080 CR3: 0000000179a9c000 CR4: 00000000001007e0
DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
DR3: 0000000000000000 DR6: 00000000ffff0ff0 DR7: 0000000000000400
Process systemled (pid: 2810, threadinfo ffff88016a204000, task ffff880179d76fa0)
Stack:
 ffffffff80271dc4 ffff880179e50ea0 0000000000000003 ffffffff80bbe670
 ffffffff80657bc0 ffff88017b02f850 ffff88016a205e88 ffffffff802878b4
 fffffffffffffff4 ffff88016a205f50 ffff8801796f4900 000000000000000a
Call Trace:
 [<ffffffff80271dc4>] ? kstrtoull+0x14/0x20
 [<ffffffff802878b4>] export_store+0x44/0xf0
 [<ffffffff80307326>] class_attr_store+0x16/0x30
 [<ffffffff801333f8>] sysfs_write_file+0xc8/0x140
 [<ffffffff800d1ed3>] vfs_write+0xa3/0x160
 [<ffffffff800d230d>] sys_write+0x4d/0xa0
 [<ffffffff805e43d2>] system_call_fastpath+0x16/0x1b
Code: fe ff ff 4d 85 ff 48 c7 c0 ca b0 7f 80 48 89 da 4c 0f 44 f8 48 8b 03 45 89 e8 4c 89 f9 48 c7 c6 08 8a 7c 80 48 c7 c7 40 3a a7 80 <48> 2b 90 80 00 00 00 48 c1 fa 03 69 d2 ab aa aa aa 03 50 78 31
RIP  [<ffffffff80285c5c>] gpiod_request+0x1ac/0x1f0
 RSP <ffff88016a205e18>
CR2: 0000000000000080
---[ end trace 7e5b53e78a1cb11e ]---
Killed

**Comment by sonoble** [comment]
Hi Audi,

I am pulling in the changes to the 3.9 kernel now.  Apologies for missing this too!

**Comment by audihsu-qci** [comment]
Hi sonoble,
    ONL is really difficult to build. Is there any better way to keep submodules dependency?

**Comment by audihsu-qci** [comment]
Hi sonoble,
    If this happens again, please check your coreboot version.
SeaBIOS (version **1.0.4.0**-42cb092-20150703_115533-ERX07-ubuntu)
The version should be **1.0.4.0** up. This supports correct dmidecode feature, which is used in ONL kernel platform driver.

**Comment by jnealtowns** [comment]
Audi,

We understand the difficulty. We have a new version of ONL coming out soon
which will remove these submodule dependencies. Bear with us until the new
structure is published.

Regards,
Jeff

**Comment by sonoble** [comment]
Hi Audi,

As Jeff noted, we are doing a re-write of the system that will remove a lot of the submodule dependencies and move most things into the main build tree.  

As for the crash, once I pulled in the changes for the kernel I am able to boot without issue on both the LY6 and LY8.

All of the changes you submitted for the LY6/LY8 should be in mainline if you want to confirm.

**Comment by audihsu-qci** [comment]
OK, thanks.
May you change the submodule commit for linux-3.9.6 and onlp-quanta?
This will help keeping the dependency currently.

**Comment by sonoble** [comment]
Hi Audi,

Those are updated by https://github.com/opennetworklinux/ONL/commit/bcae3d291793a9864e85c9f42005a4430bf4313d
and 
https://github.com/opennetworklinux/ONL/commit/a79666ce1b4354264f62ae6bc09f93e20b4b3da7

I was able to pull and build the ONL master directly and load it onto the LY6/LY8

**Pull request merged**
